// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9EPdo9hG-DsV9O7bCngOEuMVxA3e9cl4',
    appId: '1:1096026971278:web:7805a499130b33c419bddf',
    messagingSenderId: '1096026971278',
    projectId: 'studifyy-61dfb',
    authDomain: 'studifyy-61dfb.firebaseapp.com',
    storageBucket: 'studifyy-61dfb.appspot.com',
    measurementId: 'G-DWSR8V03R1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE24gLdxFnFqyRz6Ep_1ozuLI7Zkp9bZg',
    appId: '1:1096026971278:android:e07f8ac60c3b983f19bddf',
    messagingSenderId: '1096026971278',
    projectId: 'studifyy-61dfb',
    storageBucket: 'studifyy-61dfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ7QP4Fp3H_xI6uo_RaKhbGDdEtrocubY',
    appId: '1:1096026971278:ios:fb3d505899276ca619bddf',
    messagingSenderId: '1096026971278',
    projectId: 'studifyy-61dfb',
    storageBucket: 'studifyy-61dfb.appspot.com',
    iosBundleId: 'com.example.studifyy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ7QP4Fp3H_xI6uo_RaKhbGDdEtrocubY',
    appId: '1:1096026971278:ios:fb3d505899276ca619bddf',
    messagingSenderId: '1096026971278',
    projectId: 'studifyy-61dfb',
    storageBucket: 'studifyy-61dfb.appspot.com',
    iosBundleId: 'com.example.studifyy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9EPdo9hG-DsV9O7bCngOEuMVxA3e9cl4',
    appId: '1:1096026971278:web:db8759ab3bb4ad8119bddf',
    messagingSenderId: '1096026971278',
    projectId: 'studifyy-61dfb',
    authDomain: 'studifyy-61dfb.firebaseapp.com',
    storageBucket: 'studifyy-61dfb.appspot.com',
    measurementId: 'G-FYYQZY8MC1',
  );
}
